<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ameyas-MBP.fritz.box" failures="1" tests="10" name="PetTests" time="15.959" errors="0" timestamp="2025-10-01T11:14:12 CEST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.971"/>
  <testcase classname="api.test.UserTests" name="testgetUserByName" time="1.132"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="1.39"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="0.665">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUserByName(UserTests.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DataDrivenTest" name="testPostuser" time="0.614"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostuser" time="0.62"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostuser" time="0.793"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.199"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.282"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="0.623"/>
</testsuite> <!-- PetTests -->
