<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ameyas-MBP.fritz.box" failures="2" tests="10" name="PetTests" time="17.495" errors="0" timestamp="2025-10-01T11:03:00 CEST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="4.775"/>
  <testcase classname="api.test.UserTests" name="testgetUserByName" time="1.424">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testgetUserByName(UserTests.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testgetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="1.851"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="0.616"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostuser" time="0.626"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostuser" time="0.61"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostuser" time="0.696"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.203"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.298"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.236">
    <failure type="java.lang.AssertionError" message="Failed to delete user: testuser3 expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Failed to delete user: testuser3 expected [200] but found [404]
at api.test.DataDrivenTest.testDeleteUserByName(DataDrivenTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- PetTests -->
